spring:
  config:
    import: optional:configserver:http://config-server:8888
  application:
    name: product-service
  cloud:
    discovery:
      enabled: true
    config:
      fail-fast: false  
