spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://customer-db:5432/kcustomerdb
    username: damach
    password: damach

  jpa:
    hibernate:
      ddl-auto: update # Changed from update to validate for production
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  jackson:
    serialization:
      write-dates-as-timestamps: false

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
  
server:
  port: 8051
  servlet:
    context-path: /customer-service

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
      base-path: /actuator  
  endpoint:
    health:
      show-details: always