spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://order-db:5432/korderdb
    username: damach
    password: damach

  jpa:
    hibernate:
      ddl-auto: create # Changed from update to validate for production
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  jackson:
    serialization:
      write-dates-as-timestamps: false

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
  
server:
  port: 8054
  servlet:
    context-path: /order-service

application:
  config:
    customer-url: http://customer-service:8051/customer-service/api/v1/customers
    product-url: http://product-service:8052/product-service/api/v1/products
    payment-url: http://payment-service:8055/payment-service/api/v1/payments
 
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
      base-path: /actuator  
  endpoint:
    health:
      show-details: always